AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: CloudFormation template for Email Formatter Lambda function and related resources.
Parameters:
  FunctionName:
    Type: String
    Description: "Function Name"
    Default: "EmailFormatterFunction"
  FunctionBucketName:
    Type: String
    Description: "Bucket the Function package"
  FunctionKeyName:
    Type: String
    Description: "Key of the Function package on S3"
Resources:
  EmailFormatterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "email-formatter-send-queue"
  EmailFormatterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service: "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      Policies:
        -
          PolicyName: "root"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              -
                Effect: Allow
                Action:
                  - ses:SendEmail
                  - ses:SendRawEmail
                  - ses:ListVerifiedEmailAddresses
                Resource: "*"
              -
                Effect: Allow
                Action:
                  - s3:Get*
                  - s3:List*
                Resource: "*"
              -
                Effect: Allow
                Action:
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                  - sqs:ReceiveMessage
                Resource: "arn:aws:sqs:*"
  EmailFormatterFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: SQSEventHandler::handleRequest
      Runtime: java8
      CodeUri:
        Bucket: !Ref FunctionBucketName
        Key: !Ref FunctionKeyName
      FunctionName: !Ref FunctionName
      Description: "Lambda Function for the Email Formatter"
      Timeout: 15
      MemorySize: 512
      Role: !GetAtt [ "EmailFormatterRole", "Arn" ]
      Environment:
        Variables:
          SQS_QUEUE: !Ref EmailFormatterQueue
      Events:
        QueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt [ "EmailFormatterQueue", "Arn" ]
            BatchSize: 10